import type { Metadata } from "next";
import Link from "next/link";
import {
  LICENSE_PLACEHOLDER,
  MISSING,
} from "@/lib/site";
import { deliveryWindowNotice } from "@/lib/hours";
import { getStoreProfile } from "@/lib/store";

/**
 * Order confirmation.
 *
 * ── What this page is, and what it is not ─────────────────────────────────
 *
 * It is the customer's confirmation that an order was accepted, and it carries
 * the licensee identification B&P § 26151(a)(1) requires.
 *
 * It is NOT the 4 CCR § 15420 delivery request receipt. That document has nine
 * mandated elements — including the first name and EMPLOYEE NUMBER of both the
 * delivery employee and the employee who prepared the order, a
 * retailer-assigned customer number, per-line weight or volume, and the
 * customer's signature captured at handover — and it is generated by the back
 * office and handed over at the door. § 15418(f) requires it to reach the
 * driver before departure. None of those fields exist in this storefront's
 * data, and inventing a document that looks like the statutory receipt but
 * isn't would be worse than not printing one.
 *
 * ⚠️ DECLARED GAP — R&TC § 34011.2(d) excise amount.
 *    The statute requires the purchaser to be given a document that SEPARATELY
 *    STATES the cannabis excise tax. This app separates it everywhere it has
 *    the figures — cart and checkout both show a "California cannabis excise
 *    tax" line — but the placed-order record the commerce API returns carries a
 *    single `price` and no tax breakdown at all. So the AMOUNT cannot be
 *    restated here from real data, and this page says where the itemised
 *    receipt comes from instead of printing a number it would have to guess.
 *    Closing this needs a tax breakdown on the order in the back office; it is
 *    on the operator checklist in README.md.
 */

export const metadata: Metadata = { title: "Order placed" };
export const dynamic = "force-dynamic";

export default async function ConfirmationPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  // Business identity resolved server-side: dashboard value first, env
  // fallback (merged in lib/kamui/map.ts). Same names the render code always
  // used — only the source moved.
  const profile = await getStoreProfile();
  const LICENSE_NUMBER = profile.licenseNumber ?? "";
  const LEGAL_ENTITY_NAME = profile.legalEntityName ?? "";
  const POLICY_EFFECTIVE_DATE = profile.policyEffectiveDate ?? "";
  const PRIVACY_CONTACT_EMAIL = profile.privacyContactEmail ?? profile.contactEmail ?? "";
  const PRIVACY_CONTACT_ADDRESS = profile.privacyContactAddress ?? "";
  const LOCAL_PERMIT_NUMBER = profile.localPermitNumber ?? "";
  const sp = await searchParams;
  const pick = (key: string) => {
    const v = sp[key];
    return (Array.isArray(v) ? v[0] : v) ?? "";
  };
  const orderNumber = pick("order");
  const token = pick("token");

  return (
    <div className="track-card center" data-reveal>
      <span className="eyebrow" style={{ "--i": 0 } as React.CSSProperties}>
        Confirmed
      </span>

      <h1 className="display" style={{ fontSize: "var(--t-3)", margin: "0.6rem 0 1rem" }}>
        Order placed.
      </h1>

      {orderNumber ? (
        <p className="muted">
          Your order number is <strong className="num">#{orderNumber}</strong>.
        </p>
      ) : (
        <p className="muted">We&apos;ve received your order.</p>
      )}

      <p className="muted">
        We&apos;ll text you when a driver is on the way. Have cash ready, and a valid, unexpired
        government-issued photo ID — the driver has to check it in person and cannot complete the
        delivery without it.
      </p>

      <p className="faint">{deliveryWindowNotice()}</p>

      <div className="row mt-3" style={{ justifyContent: "center" }}>
        {token ? (
          <Link className="btn" href={`/track/${encodeURIComponent(token)}`}>
            Track this order
          </Link>
        ) : null}
        <Link className="btn btn-ghost" href="/">
          Keep shopping
        </Link>
      </div>

      {/* R&TC § 34011.2(d). The excise tax is separately stated on the itemised
          receipt handed over at delivery — see the file header for why the
          amount is not restated here. Note what is deliberately NOT printed:
          "The cannabis excise taxes are included in the total amount of this
          invoice." That sentence was mandated by the former § 34011(a)(2),
          which became inoperative on 1 April 2023, and printing it today is
          affirmatively wrong. */}
      <p className="faint mt-3 mb-1">
        Your itemised receipt is handed over with the delivery. It states the California cannabis
        excise tax separately from sales tax, as required by Revenue &amp; Taxation Code
        § 34011.2(d).
      </p>

      {/* B&P § 26151(a)(1) — this screen is the customer's record of who sold
          to them, so it identifies the licensee, not just the shop name. */}
      <p className="faint mb-0">
        Sold by{" "}
        <span className="license" data-missing={!LEGAL_ENTITY_NAME}>
          {LEGAL_ENTITY_NAME || MISSING("Legal entity name")}
        </span>{" "}
        · DCC Licence{" "}
        <span className="license" data-missing={!LICENSE_NUMBER}>
          {LICENSE_NUMBER || LICENSE_PLACEHOLDER}
        </span>
        {LOCAL_PERMIT_NUMBER ? (
          <>
            {" "}
            · Local permit <span className="license">{LOCAL_PERMIT_NUMBER}</span>
          </>
        ) : null}
      </p>
    </div>
  );
}
